services:
  node-api:
    build: .
    container_name: news-app-auto-api
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - PORT=80
      - DB_URL=${DB_URL}
    networks:
      - web
      - backend

networks:
  web:
    external: true
  backend:
    external: true