import { z } from 'zod';

// ─── Stage 1: Web Search Candidates ──────────────────────────────────────────

export const candidateStorySchema = z
  .object({
    title: z.string().min(1),
    url: z.string().min(1).refine(
      (value) => /^https?:\/\/\S+/i.test(value),
      'url must be a valid http(s) URL',
    ),
    snippet: z.string().min(1),
    sourceDomain: z.string().min(1),
  })
  .strict();

export type CandidateStory = z.infer<typeof candidateStorySchema>;

export const candidateBatchSchema = z
  .object({
    candidates: z.array(candidateStorySchema).min(1).max(30),
  })
  .strict();

export type CandidateBatch = z.infer<typeof candidateBatchSchema>;

// ─── Stage 2: Classification ──────────────────────────────────────────────────

export const classificationItemSchema = z
  .object({
    candidateIndex: z.number().int().min(0),
    legitimacyScore: z.number().min(0).max(1),
    isDuplicate: z.boolean(),
    subTopic: z.string().min(1),
  })
  .strict();

export type ClassificationItem = z.infer<typeof classificationItemSchema>;

export const classificationBatchSchema = z
  .object({
    classifications: z.array(classificationItemSchema),
  })
  .strict();

export type ClassificationBatch = z.infer<typeof classificationBatchSchema>;

// ─── Stage 4: Synthesized Briefs ──────────────────────────────────────────────
// Sources are NOT included here — they are populated from real cluster URLs,
// never generated by the model.

export const synthesizedBriefItemSchema = z
  .object({
    clusterIndex: z.number().int().min(0),
    title: z.string().min(1),
    summary: z.string().min(1),
  })
  .strict();

export type SynthesizedBriefItem = z.infer<typeof synthesizedBriefItemSchema>;

export const synthesizedBriefBatchSchema = z
  .object({
    briefs: z.array(synthesizedBriefItemSchema).min(0),
  })
  .strict();

export type SynthesizedBriefBatch = z.infer<typeof synthesizedBriefBatchSchema>;

